# Generated by Django 2.2.1 on 2019-06-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RaffleEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raffle', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('paypal_email', models.EmailField(max_length=30)),
                ('instagram', models.CharField(max_length=30)),
                ('phone_prefix', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('street1', models.CharField(max_length=30)),
                ('street2', models.CharField(max_length=30)),
                ('zipcode', models.CharField(max_length=30)),
                ('county', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('shoe_size', models.TextField(max_length=30)),
                ('api_key', models.CharField(max_length=30)),
                ('threads', models.CharField(max_length=30)),
                ('cardname', models.CharField(max_length=30)),
                ('cardnumber', models.CharField(max_length=30)),
                ('cc_exp_mo', models.CharField(max_length=30)),
                ('cc_exp_yr', models.CharField(max_length=30)),
                ('cvc', models.CharField(max_length=30)),
            ],
        ),
    ]
