# Generated by Django 2.2.1 on 2019-06-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffle_form', '0002_auto_20190614_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffleentry',
            name='address',
            field=models.CharField(max_length=60),
        ),
    ]
