# Generated by Django 2.2.1 on 2019-06-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffle_form', '0003_auto_20190614_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffleentry',
            name='api_key',
            field=models.CharField(max_length=50),
        ),
    ]
